### ISSUE TITLE
For server side rendering, we need Radium server side

### ISSUE THREAD

**Issue by fabien-h** [markoshust/meteor-radium#1]
Because it's used in the components you build :)

**Comment by markshust** [comment]
I'll be glad to take a PR ;) I'm new to Meteor packaging, so need some extra hands of help here.

**Comment by markshust** [comment]
Added with https://github.com/markoshust/meteor-radium/pull/3

**Comment by markshust** [comment]
Published to atmosphere in 0.1.0 https://atmospherejs.com/markoshust/radium
