### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by elie222** [markoshust/meteor-radium#6]
How is this package used? Meteor is complaining to me about decorators not being recognised when I try to use it.

**Comment by markshust** [comment]
Sorry I didn't provide an example in the readme. Afaik decorators aren't generally setup for Meteor right now. You can use the alternate method of wrapping the React component within `Radium()`. I'll leave this ticket open to update the readme with an example.

**Comment by elie222** [comment]
Thanks. I found the relevant info in the docs and made a pull request with a short explanation: https://github.com/markoshust/meteor-radium/pull/7

**Comment by markshust** [comment]
Awesome thanks
